### PR TITLE
*Switched to this project* New M16_lab02.md file

### PR DESCRIPTION
**Pull request by osheaanaya**
O'shea Anaya & Shane Masuda 
New M16_lab02.md file   *250 Points Request

### CODE REVIEW

**Comment by osheaanaya** [comment]
Updated README.md:
Fixes Issue #1 *100 points request
Fixes Issue #2 
Fixes Issue #3

**Comment by osheaanaya** [comment]
Fixes Issue #10 *100 points request
- New Simple Guessing Game App (Link In README.md)

**Comment by osheaanaya** [comment]
Fixes Issue #8 *100 points request

**Comment by osheaanaya** [comment]
Fixes Issue #9 *100 Points request
     -  Added the companion app for the Save State Tutorial  *100 Points request (This is an additional 100 points request) -Nate suggested I request 100 for the Save State Tutorial and another 100 for the companion app for the tutorial.

**Comment by pconrad** [comment]
This pull request replaced by this one that goes into a separate oshea branch of the repo.

https://github.com/UCSB-CS56-Projects/cs56-android-getting-started/pull/17

**Comment by osheaanaya** [comment]
I'm adding another comment in case you missed my updated comment
Fixes Issue #9 *100 Points request
- Added the companion app for the Save State Tutorial *100 Points request (This is an additional 100 points request) -Nate suggested I request 100 for the Save State Tutorial and another 100 for the companion app for the tutorial.

**Pull request closed without merging**
